#!/bin/bash

LQL_QUERY=`ls *.lql`
LQL_POLICY=`ls *.pol`
LQL_NAME=`grep queryId $LQL_QUERY | awk '{print $2}'`
echo "QueryId=$LQL_NAME"

LQL_EXISTS=`lacework query list | grep $LQL_NAME`

if [ "$LQL_EXISTS" ]; then
   echo "QueryID exists, calling update instead of create"
   lacework lql update -f $LQL_QUERY
else
   echo "Creating Query"
   lacework lql create -f $LQL_QUERY
fi


POL_NAME=`grep policyId $LQL_POLICY | sed 's/"//g' | sed 's/,//g' | awk '{print $2}'`
echo "PolicyID=$POL_NAME"

POL_EXISTS=`lacework policy list | grep $POL_NAME | awk '{print $1}'`
if [ "$POL_EXISTS" ]; then
	echo "Policy Exists, updating"
	echo "Create temporary file replacing $POL_NAME with $POL_EXISTS"
	cat $LQL_POLICY | sed 's/'$POL_NAME'/'$POL_EXISTS'/' > $LQL_POLICY.UPDATE
	lacework policy update -f $LQL_POLICY.UPDATE
	rm $LQL_POLICY.UPDATE
else
	echo "Creating policy"
        lacework policy create -f $LQL_POLICY
fi

